setup:
  type: list
  default: ''
  description: |
    Each line should be in the format of "<code>category name</code>, <code>command</code>, <code>value</code>"

    List of available commands and values:
    <ul>
      <li><code>sidebar</code>
        <ul>
          <li>Allowed value: one of <code>left</code>, <code>right</code></li>
          <li>Default: <code>right</code></li>
        </ul>
      </li>
      <li><code>style</code>:
        <ul>
          <li>Allowed value: <code>no-bullets</code></li>
          <li>Default: blank</li>
        </ul>
      </li>
      <li><code>post</code>
        <ul>
          <li>Integer <code>post_id</code></li>
          <li>this can be found by inspecting the HTML source of a post <code>data-post-id=xxxx</code></li>
        </ul>
      </li>
    </ul>
